In [6]:
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import utilsCM

from tqdm import tqdm

In [7]:
#Load word2sense
#already preprocessed in MATLAB so that Wrd2Sns and THINGs overlap --> we have IMAGES, LABELS and SENSES
pathtofile = '../code-00-preprocessdataset/'
Y_embeddings = pd.read_csv(pathtofile + "ThingsWrd2Sns.txt", sep=",")
Y_embeddings = Y_embeddings.values[:,1:Y_embeddings.shape[1]-1].astype(np.float)

In [8]:
keyword = {'ROIpred'}
# keyword = {'DNNActvtn'}

# layer =  {'conv_1', 'conv_2','conv_3','conv_4','conv_5'}
layer =  {'conv_5'}

# ROI = {'EVC','LOC','PFS','OPA','PPA','RSC','FFA','OFA','STS','EBA'}
ROI = {'EVC','LOC','PPA'}
# ROI = {'EVC','PPA'}

Sub = [1,2,3,4]

#how many components to keep?
Keepncomps = [40]
# Keepncomps = [10,40,80]

# kf = KFold(n_splits = 9)


In [9]:
for ilayer in layer:
    for ikeyword in keyword:
        
        if ikeyword is 'ROIpred':
            
            for iROI in ROI:
                
                predictor_variable = {}
                for iSub in Sub:
                    thisSub = np.load(os.getcwd() + '/data-00/' +  "ROIpred_Sub" + str(iSub) + '_' + iROI + "_" + ilayer + '.npy')
                    #load ROIpred as predictor variable
                    if iSub is 1:
                        predictor_variable = thisSub
                    else:
                        predictor_variable = np.append( predictor_variable , thisSub, axis = 1)

                for icomps in Keepncomps:
                    mean_r = {}
                    mean_r = utilsCM.iter_cvregress(predictor_variable,Y_embeddings,ikeyword,ilayer,icomps,iROI,datapath='data-01/')
#                     utilsCM.make_figure(mean_r,ikeyword,ilayer,icomps,iROI, figurepath = 'figures-01/')
#                     print(mean_r)
        
        
        elif ikeyword is 'DNNActvtn':
            predictor_variable = pd.read_csv(os.getcwd() + '/data-00/' +  "things_" + ilayer + '.csv', header=None, index_col=0).iloc[:,:].to_numpy()
            for icomps in Keepncomps:
                mean_r = {}
                mean_r = utilsCM.iter_cvregress(predictor_variable,Y_embeddings,ikeyword,ilayer,icomps,datapath='data-01/')
#                 utilsCM.make_figure(mean_r,ikeyword,ilayer,icomps, figurepath = 'figures-01/')

k-fold regression, independet variable: 40 PCs retained of ROIpred from LOC


/Users/cmagri1/OneDrive - Johns Hopkins/Project-Word2Sense/Code-Python/semantic-code/cm/code-01-analysis/utilsCM.py:132: RuntimeWarning: invalid value encountered in true_divide
  zs = lambda v: (v - v.mean(0)) / v.std(0)
/Users/cmagri1/OneDrive - Johns Hopkins/Project-Word2Sense/Code-Python/semantic-code/cm/code-01-analysis/utilsCM.py:132: RuntimeWarning: invalid value encountered in true_divide
  zs = lambda v: (v - v.mean(0)) / v.std(0)
/Users/cmagri1/OneDrive - Johns Hopkins/Project-Word2Sense/Code-Python/semantic-code/cm/code-01-analysis/utilsCM.py:132: RuntimeWarning: invalid value encountered in true_divide
  zs = lambda v: (v - v.mean(0)) / v.std(0)
/Users/cmagri1/OneDrive - Johns Hopkins/Project-Word2Sense/Code-Python/semantic-code/cm/code-01-analysis/utilsCM.py:132: RuntimeWarning: invalid value encountered in true_divide
  zs = lambda v: (v - v.mean(0)) / v.std(0)
/Users/cmagri1/OneDrive - Johns Hopkins/Project-Word2Sense/Code-Python/semantic-code/cm/code-01-analysis/utilsCM

k-fold regression, independet variable: 40 PCs retained of ROIpred from EVC


/Users/cmagri1/OneDrive - Johns Hopkins/Project-Word2Sense/Code-Python/semantic-code/cm/code-01-analysis/utilsCM.py:132: RuntimeWarning: invalid value encountered in true_divide
  zs = lambda v: (v - v.mean(0)) / v.std(0)
/Users/cmagri1/OneDrive - Johns Hopkins/Project-Word2Sense/Code-Python/semantic-code/cm/code-01-analysis/utilsCM.py:132: RuntimeWarning: invalid value encountered in true_divide
  zs = lambda v: (v - v.mean(0)) / v.std(0)
/Users/cmagri1/OneDrive - Johns Hopkins/Project-Word2Sense/Code-Python/semantic-code/cm/code-01-analysis/utilsCM.py:132: RuntimeWarning: invalid value encountered in true_divide
  zs = lambda v: (v - v.mean(0)) / v.std(0)
/Users/cmagri1/OneDrive - Johns Hopkins/Project-Word2Sense/Code-Python/semantic-code/cm/code-01-analysis/utilsCM.py:132: RuntimeWarning: invalid value encountered in true_divide
  zs = lambda v: (v - v.mean(0)) / v.std(0)
/Users/cmagri1/OneDrive - Johns Hopkins/Project-Word2Sense/Code-Python/semantic-code/cm/code-01-analysis/utilsCM

k-fold regression, independet variable: 40 PCs retained of ROIpred from PPA


/Users/cmagri1/OneDrive - Johns Hopkins/Project-Word2Sense/Code-Python/semantic-code/cm/code-01-analysis/utilsCM.py:132: RuntimeWarning: invalid value encountered in true_divide
  zs = lambda v: (v - v.mean(0)) / v.std(0)
/Users/cmagri1/OneDrive - Johns Hopkins/Project-Word2Sense/Code-Python/semantic-code/cm/code-01-analysis/utilsCM.py:132: RuntimeWarning: invalid value encountered in true_divide
  zs = lambda v: (v - v.mean(0)) / v.std(0)
/Users/cmagri1/OneDrive - Johns Hopkins/Project-Word2Sense/Code-Python/semantic-code/cm/code-01-analysis/utilsCM.py:132: RuntimeWarning: invalid value encountered in true_divide
  zs = lambda v: (v - v.mean(0)) / v.std(0)
/Users/cmagri1/OneDrive - Johns Hopkins/Project-Word2Sense/Code-Python/semantic-code/cm/code-01-analysis/utilsCM.py:132: RuntimeWarning: invalid value encountered in true_divide
  zs = lambda v: (v - v.mean(0)) / v.std(0)
/Users/cmagri1/OneDrive - Johns Hopkins/Project-Word2Sense/Code-Python/semantic-code/cm/code-01-analysis/utilsCM

In [36]:
# filename_PPA = 'PredictSENSES_' + 'ROIpred' + '_'+ 'PPA'+'_'+ ilayer+ '_'+ str(icomps) +'PCs'
# thisPrediction_PPA = np.load(os.getcwd() + '/data-01/' + filename_PPA + '.npy')

# filename_EVC = 'PredictSENSES_' + 'ROIpred' + '_'+ 'EVC'+'_'+ ilayer + '_'+ str(icomps) +'PCs'
# thisPrediction_EVC = np.load(os.getcwd() + '/data-01/' + filename_EVC + '.npy')

# filename_LOC = 'PredictSENSES_' + 'ROIpred' + '_'+ 'LOC'+'_'+ ilayer + '_'+ str(icomps) +'PCs'
# thisPrediction_LOC = np.load(os.getcwd() + '/data-01/' + filename_LOC + '.npy')

# filename_DNN = 'PredictSENSES_' + 'DNNActvtn' +'_'+ ilayer + '_'+ str(icomps) +'PCs'
# thisPrediction_DNN = np.load(os.getcwd() + '/data-01/' + filename_DNN + '.npy')

In [37]:
# thisPrediction_PPA

array([0.16496019, 0.10114301, 0.12379206, ..., 0.12305212, 0.03688815,
       0.09418609])

In [38]:
# thisPrediction_EVC

array([0.1727825 , 0.15557366, 0.11384222, ..., 0.12834745, 0.06006222,
       0.09842186])

In [39]:
# thisPrediction_LOC

array([0.17595037, 0.15143328, 0.09116192, ..., 0.15350086, 0.09900339,
       0.08840063])